disabled_rules:
  - trailing_whitespace
  - todo
  - line_length

opt_in_rules:
  - empty_count
  - explicit_init
  - first_where
  - force_unwrapping
  - implicit_return
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_imports

included:
  - Sources
  - Tests

excluded:
  - .build
  - .swiftpm
  - Package.swift

line_length:
  warning: 120
  error: 200

function_body_length:
  warning: 50
  error: 100

type_body_length:
  warning: 200
  error: 400

file_length:
  warning: 500
  error: 1200

cyclomatic_complexity:
  warning: 10
  error: 20

identifier_name:
  min_length:
    warning: 3
    error: 2
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - url
    - api

force_cast: error
force_try: error
force_unwrapping: error

custom_rules:
  no_print:
    name: "No Print"
    regex: "print\\("
    message: "Use Logger instead of print()"
    severity: warning