# Test configuration for Swift Embedded mode
esphome_swift:
  name: "test_swift_embedded"

esp32:
  board: esp32-c6-devkitc-1
  framework:
    type: swift-embedded

# Basic GPIO components for testing
switch:
  - platform: gpio
    pin:
      number: 5
    name: "LED Switch"
    id: led_switch
    restore_mode: RESTORE_DEFAULT_OFF

binary_sensor:
  - platform: gpio
    pin:
      number: 9
    name: "Button"
    id: button_sensor
    inverted: true

# Test sensor
sensor:
  - platform: adc
    pin:
      number: 1
    name: "Battery Voltage"
    id: battery_sensor
    update_interval: 60s
    attenuation: db11
    filters:
      - type: multiply
        value: 3.3